#!/bin/bash

# Install vim-plug
if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +PlugInstall
fi

# Update/install plugins
vim +PlugUpdate +qall
