#!/bin/bash

# Install Vundle
if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  mkdir -p $HOME/.vim/bundle
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

# Update/install plugins
vim +PluginClean +PluginInstall +qall
