" Ideas -
" http://pacuna.io/2015/02/09/vim-on-rails/
" https://github.com/pacuna/vimrc/blob/master/vimrc

" Vundle stuff
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-vinegar'    " File browsing
Plugin 'tpope/vim-commentary' " Easy comment toggling
Plugin 'tpope/vim-fugitive'   " Git commands
Plugin 'kien/ctrlp.vim'       " Fuzzy search
Plugin 'scrooloose/syntastic' " Syntax checking
Plugin 'gregsexton/MatchTag'  " matching HTML tag highlighting
Plugin 'dougireton/vim-chef'  " Chef syntax and syntastic support
Plugin 'scrooloose/nerdtree'  " Project drawer
Plugin 'Xuyuanp/nerdtree-git-plugin' "Git status for NERDTree
Plugin 'chriskempson/base16-vim'
call vundle#end()                " required
filetype plugin indent on        " required
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" For MacVim (and others?)
colorscheme slate

" For Everything
syntax on
set noautoindent
"set number
set incsearch	" Find the next match as we type the search
set hlsearch	" Highlight search by default
set paste	" Don't retab everything when pasting

" Move between splits/windows
nnoremap <C-h> <C-W>h 
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-l> <C-W>l

" Make tabs a bit more accessible
nnoremap th  :tabfirst<CR>
nnoremap tj  :tabnext<CR>
nnoremap tk  :tabprev<CR>
nnoremap tl  :tablast<CR>
nnoremap tt  :tabnew<cr>
nnoremap tn  :tabnext<cr>
nnoremap tm  :tabm<Space>
nnoremap td  :tabclose<CR>

" Swap words
:nnoremap <silent> gw "_yiw:s/\(\%#\w\+\)\(\W\+\)\(\w\+\)/\3\2\1/<CR><c-o><c-l>

" Autocomplete HTML tags
:iabbrev </ </<C-X><C-O>

" Write with sudo
cmap w!! w !sudo tee > /dev/null %

" Syntastic Recommendations
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0

" Enable neocomplete
" let g:neocomplete#enable_at_startup = 1

" Automatically change current directory
" http://vim.wikia.com/wiki/Set_working_directory_to_the_current_file
autocmd BufEnter * silent! lcd %:p:h

" NERDTree Customization
" Start NERDTree when no files opened
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" Toggle
map <C-d> :NERDTreeToggle<CR>
" Close vim if no other windows than NERDTree are open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Color text if over 80 columns
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

let base16colorspace=256
set background=dark
colorscheme base16-default
