#!/bin/bash

if [ -d ${HOME}/.hooks ]; then
  for file in `ls $HOME/.hooks/*_post-up`
  do
    echo Running post_up hook for `basename $file | cut -d'_' -f1`
    $file
  done
fi

if [ ! -d ${HOME}/.oh-my-zsh ]; then
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ]; then
  echo "Installing powerlevel10k"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

plugins="zsh-autosuggestions zsh-syntax-highlighting zsh-completions zsh-history-substring-search"
for plugin in `echo $plugins`;
do
  [[ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/${plugin} ]] && \
    git clone https://github.com/zsh-users/${plugin} ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/${plugin}
done
