#!/bin/zsh

if [ -d ${HOME}/.hooks ]; then
  for file in `ls $HOME/.hooks/*_post-up`
  do
    echo Running post_up hook for `basename $file | cut -d'_' -f1`
    $file
  done
fi

source ${HOME}/.zshenv
if [ ! -d ${XDG_CONFIG_HOME}/zsh/.zprezto ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/.zprezto"
  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md; do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
fi
