#!/bin/bash

if [ -d ${HOME}/.hooks ]; then
  for file in `ls $HOME/.hooks/*_post-up`
  do
    echo Running post_up hook for `basename $file | cut -d'_' -f1`
    $file
  done
fi

if [ ! -d ${HOME}/.oh-my-zsh ]; then
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
