#!/bin/bash

export RBENV_DIR="$HOME/.rbenv"
export RBENV_PLUGINS="$RBENV_DIR/plugins"

if [ ! -e $RBENV_DIR ]; then
  git clone https://github.com/rbenv/rbenv $RBENV_DIR
fi

if [ ! -e $RBENV_PLUGINS ]; then
  mkdir $RBENV_PLUGINS
  git clone https://github.com/rbenv/ruby-build $RBENV_PLUGINS/ruby-build
  git clone https://github.com/rkh/rbenv-update $RBENV_PLUGINS/rbenv-update
  git clone https://github.com/rbenv/rbenv-default-gems $RBENV_PLUGINS/rbenv-default-gems
  git clone https://github.com/docwhat/rbenv-chefdk $RBENV_PLUGINS/rbenv-chefdk
  mkdir -p $RBENV_DIR/versions/chefdk
else
  rbenv update
fi
