#!/bin/bash

if [ ! -e $HOME/.rbenv/plugins ]; then
  cd $HOME/.rbenv/plugins
  git clone https://github.com/sstephenson/ruby-build
  git clone https://github.com/rkh/rbenv-update
  git clone https://github.com/sstephenson/rbenv-gem-rehash
  git clone https://github.com/sstephenson/rbenv-default-gems
  #git clone https://github.com/jf/rbenv-gemset
  git clone https://github.com/SeanSith/rbenv-chefdk
  cd -
  mkdir -p $HOME/.rbenv/versions/chefdk
else
  rbenv update
fi
